=== michaelBedDev/XPATH/EX6 customer/xslt/customer.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="customer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="first" type="xs:string" />
                            <xs:element name="middle" />
                            <xs:element name="last" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="address">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="street" type="xs:string" />
                            <xs:element name="city" type="xs:string" />
                            <xs:element name="state" />
                            <xs:element name="country" type="xs:string" />
                            <xs:element name="postalcode" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== michaelBedDev/XPATH/EX6 customer/xslt/customer.xml
<customer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="customer.xsd" id="id_12345567">
    <name>
        <first>Sherlock</first>
        <middle></middle>
        <last>Holmes</last>
    </name>
    <address>
        <street>221b Baker Street</street>
        <city>London</city>
        <state></state>
        <country>England</country>
        <postalcode>W1U</postalcode>
    </address>
</customer>
